
/**
 * CORE TYPE DEFINITIONS
 * Strict typing to prevent "zombie" data and layout crashes.
 */

// ---------------------------------------------------------------------------
// PRIMITIVES
// ---------------------------------------------------------------------------

// ISO Date String: "YYYY-MM-DD" ONLY. No time component.
export type ISODate = string;

// Time String: "HH:mm" (24h format).
export type ISOTime = string;

// Unique Identifier
export type TaskId = string;

// RRule String
export type RecurrenceRuleString = string;

// Recurrence Specifics
export type RecurrenceFrequency = 'daily' | 'weekly' | 'monthly' | 'yearly';
export type WeekDay = 'MO' | 'TU' | 'WE' | 'TH' | 'FR' | 'SA' | 'SU';

// ---------------------------------------------------------------------------
// ENUMS & CONSTANTS
// ---------------------------------------------------------------------------

export type TaskType = 'task' | 'event' | 'work' | 'chore' | 'habit';

export interface RecurrenceConfig {
    frequency: RecurrenceFrequency;
    interval: number;
    endDate?: ISODate;
    occurrenceCount?: number;
    daysOfWeek?: WeekDay[]; 
}

// ---------------------------------------------------------------------------
// DOMAIN MODELS
// ---------------------------------------------------------------------------

export interface Task {
    // Identity
    id: TaskId;
    title: string;

    // Scheduling (Strict Separation)
    date: ISODate; // The "do date"
    time?: ISOTime; // Optional specific time
    deadline?: ISODate; // Optional strict deadline

    // Recurrence (Master Only)
    rrule?: RecurrenceRuleString;
    recurrence?: RecurrenceConfig; // UI Helper Object
    seriesId?: string; // Links instance to master

    // State
    isCompleted: boolean;
    completedAt?: number; // Unix Epoch: The time this task was finalized
    completedDates?: ISODate[]; // For Master tasks: which instances are done
    exceptionDates?: ISODate[]; // For Master tasks: which instances are skipped/moved

    // Progress
    progress?: number; // 0-100
    estimatedTime?: string; // "30m", "1h"

    // Subtasks & More (Adding common feature fields)
    subtasks?: any[]; 
    tagIds?: string[];
    importance?: number; // 0=None, 1=Low, 2=Medium, 3=High
    sortOrder?: number; // UI Reorder positioning

    // Reminders
    reminderDate?: ISODate;
    reminderTime?: ISOTime;
    reminderEnabled?: boolean;

    // Appearance
    color?: string;
    type: TaskType;

    // Metadata
    created_at: number;
    updated_at: number;    // Local storage always uses Epoch numbers
    deleted_at?: number;   // Local storage always uses Epoch numbers
    _isDirty?: boolean;    // Sync flag: true if local change is not yet pushed
    originalTaskId?: string; // Traceability for ghosts/clones
    daysRolled?: number;
    originalDate?: ISODate;
}

export interface DailyData {
    date: ISODate;
    rating?: number;
    reflection?: string;
    updated_at: number;    // Standardized to number
    deleted_at?: number;   // Standardized to number
    _isDirty?: boolean;
    isStarred?: boolean;
}

// ---------------------------------------------------------------------------
// PROJECTION MODELS (View Layer)
// ---------------------------------------------------------------------------

// What the UI actually renders (derived from Task)
export interface ProjectedTask extends Task {
    // Contextual Info
    isGhost: boolean; // Is this a projected instance?
    originalDate: ISODate; // The date generated by RRule
    daysRolled: number; // Rollover count
}
