
/**
 * CORE TYPE DEFINITIONS
 * Strict typing to prevent "zombie" data and layout crashes.
 */

// ---------------------------------------------------------------------------
// PRIMITIVES
// ---------------------------------------------------------------------------

// ISO Date String: "YYYY-MM-DD" ONLY. No time component.
export type ISODate = string;

// Time String: "HH:mm" (24h format).
export type ISOTime = string;

// Unique Identifier
export type TaskId = string;

// RRule String
export type RecurrenceRuleString = string;

// ---------------------------------------------------------------------------
// ENUMS & CONSTANTS
// ---------------------------------------------------------------------------

export type TaskType = 'task' | 'event' | 'work' | 'chore' | 'habit';

export interface RecurrenceConfig {
    frequency: 'daily' | 'weekly' | 'monthly' | 'yearly';
    interval: number;
    endDate?: ISODate;
    occurrenceCount?: number;
    daysOfWeek?: number[]; // 0=Sunday, 6=Saturday
}

// ---------------------------------------------------------------------------
// DOMAIN MODELS
// ---------------------------------------------------------------------------

export interface Task {
    // Identity
    id: TaskId;
    title: string;

    // Scheduling (Strict Separation)
    date: ISODate; // The "do date"
    time?: ISOTime; // Optional specific time
    deadline?: ISODate; // Optional strict deadline

    // Recurrence (Master Only)
    rrule?: RecurrenceRuleString;
    recurrence?: RecurrenceConfig; // UI Helper Object
    seriesId?: string; // Links instance to master

    // State
    isCompleted: boolean;
    completedDates: ISODate[]; // For Master tasks: which instances are done
    exceptionDates: ISODate[]; // For Master tasks: which instances are skipped/moved

    // Progress
    progress: number; // 0-100
    estimatedTime?: string; // "30m", "1h"

    // Appearance
    color?: string;
    type: TaskType;

    // Metadata
    createdAt: number;
    updatedAt: number;
    originalTaskId?: string; // Traceability for ghosts/clones
    importance?: number; // 0=None, 1=Low, 2=Medium, 3=High
}

// ---------------------------------------------------------------------------
// PROJECTION MODELS (View Layer)
// ---------------------------------------------------------------------------

// What the UI actually renders (derived from Task)
export interface ProjectedTask extends Task {
    // Contextual Info
    isGhost: boolean; // Is this a projected instance?
    originalDate: ISODate; // The date generated by RRule
    daysRolled: number; // Rollover count
}
